name: Docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    if: github.repository_owner  == 'ExceptionHandlersUOA'
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Build frontend
        run: |
          docker build -t ghcr.io/exceptionhandlersuoa/frontend:latest .
     
      - name: Push frontend
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ExceptionHandlersUOA --password-stdin
          docker push ghcr.io/exceptionhandlersuoa/frontend:latest

      - name: Send discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "🚀 Published Frontend 🚀"
          
      - name: Purge Camo
        uses: kevincobain2000/action-camo-purge@v1
